### ISSUE TITLE
Error install- what am i doing wrong?

### ISSUE THREAD

**Issue by abir1909** [epitron/mitm-adblock#10]
Building wheel for pyre2 (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/6q/k62zqc0x2_1gdjsb77y6q0cr0000gn/T/tmpo7ongjl1
       cwd: /private/var/folders/6q/k62zqc0x2_1gdjsb77y6q0cr0000gn/T/pip-req-build-nn6svfgl
  Complete output (95 lines):
  running bdist_wheel
  running build
  running build_ext
  -- The CXX compiler identification is AppleClang 12.0.5.12050022
  -- The C compiler identification is AppleClang 12.0.5.12050022
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Could NOT find pybind11 (missing: pybind11_DIR)
  -- Fetching pybind11 from github
  -- pybind11 v2.6.1
  -- Found PythonInterp: /usr/local/Cellar/python@3.9/3.9.7/bin/python3.9 (found version "3.9.7")
  -- Found PythonLibs: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- Performing Test HAS_FLTO_THIN
  -- Performing Test HAS_FLTO_THIN - Success
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
  -- Found Threads: TRUE
  -- Found Cython: /private/var/folders/6q/k62zqc0x2_1gdjsb77y6q0cr0000gn/T/pip-build-env-ez2pl7jy/overlay/bin/cython
  -- Could NOT find re2 (missing: re2_DIR)
  -- Trying PkgConfig
  CMake Error at /private/var/folders/6q/k62zqc0x2_1gdjsb77y6q0cr0000gn/T/pip-build-env-ez2pl7jy/overlay/lib/python3.9/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
  Call Stack (most recent call first):
    /private/var/folders/6q/k62zqc0x2_1gdjsb77y6q0cr0000gn/T/pip-build-env-ez2pl7jy/overlay/lib/python3.9/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
    /private/var/folders/6q/k62zqc0x2_1gdjsb77y6q0cr0000gn/T/pip-build-env-ez2pl7jy/overlay/lib/python3.9/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.21/Modules/FindPkgConfig.cmake:70 (find_package_handle_standard_args)
    src/CMakeLists.txt:44 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/6q/k62zqc0x2_1gdjsb77y6q0cr0000gn/T/pip-req-build-nn6svfgl/build/temp.macosx-11-x86_64-3.9/CMakeFiles/CMakeOutput.log".
  See also "/private/var/folders/6q/k62zqc0x2_1gdjsb77y6q0cr0000gn/T/pip-req-build-nn6svfgl/build/temp.macosx-11-x86_64-3.9/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 221, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 116, in <module>
      setup(
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
      _build_ext.build_ext.build_extensions(self)
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "setup.py", line 108, in build_extension
      subprocess.check_call(
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/6q/k62zqc0x2_1gdjsb77y6q0cr0000gn/T/pip-req-build-nn6svfgl', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/6q/k62zqc0x2_1gdjsb77y6q0cr0000gn/T/pip-req-build-nn6svfgl/build/lib.macosx-11-x86_64-3.9/', '-DPYTHON_EXECUTABLE=/usr/local/Cellar/python@3.9/3.9.7/bin/python3.9', '-DSCM_VERSION_INFO=0.3.6', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-GNinja']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pyre2
Failed to build pyre2
ERROR: Could not build wheels for pyre2 which use PEP 517 and cannot be installed directly

**Comment by VoidAny** [comment]
I would recommend going to the [pyre2 github page](https://github.com/andreasvc/pyre2/) and following the instructions there to build pyre2. After that, make sure you have all of the other dependencies installed by doing `cat requirements.txt` and using pip3 to install them.

That is what I did, and it worked for me.
