### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by ghost** [epitron/mitm-adblock#15]
I have tried setting it up on a linux machine but i get errors when installing python dependencies. 

Please make a documentation for it

**Comment by ghost** [comment]
For example:

Traceback (most recent call last):
  File "/usr/local/bin/mitmdump", line 8, in <module>
    sys.exit(mitmdump())
  File "/usr/local/lib/python3.8/dist-packages/mitmproxy/tools/_main.py", line 152, in mitmdump
    from mitmproxy.tools import dump
  File "/usr/local/lib/python3.8/dist-packages/mitmproxy/tools/dump.py", line 1, in <module>
    from mitmproxy import addons
  File "/usr/local/lib/python3.8/dist-packages/mitmproxy/addons/__init__.py", line 13, in <module>
    from mitmproxy.addons import proxyauth
  File "/usr/local/lib/python3.8/dist-packages/mitmproxy/addons/proxyauth.py", line 3, in <module>
    import ldap3
  File "/usr/local/lib/python3.8/dist-packages/ldap3/__init__.py", line 139, in <module>
    from .core.connection import Connection
  File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 44, in <module>
    from ..operation.compare import compare_operation, compare_request_to_dict
  File "/usr/local/lib/python3.8/dist-packages/ldap3/operation/compare.py", line 28, in <module>
    from ..operation.search import ava_to_dict
  File "/usr/local/lib/python3.8/dist-packages/ldap3/operation/search.py", line 41, in <module>
    from pyasn1.error import PyAsn1UnicodeDecodeError
ImportError: cannot import name 'PyAsn1UnicodeDecodeError' from 'pyasn1.error' (/usr/lib/python3/dist-packages/pyasn1/error.py)

everything is installed
