### ISSUE TITLE
AttributeError: type object 'SettingsFrame' has no attribute 'ENABLE_CONNECT_PROTOCOL'

### ISSUE THREAD

**Issue by apocalypse2012** [epitron/mitm-adblock#5]
Trying to get this running per the instructions in the readme. Its failing on Start. I had to make one modification to the code that I believe to be unrelated. Lines 8 and 9 of adblock.py have been modified as follows:
#import re2
import re as re2

This was required as re2 will not compile for raspberry pi.
Platform RPi 4, 8gig
Raspian Buster, 32bit

pi@servinator:~/mitm-adblock $ ./go -d
* Starting proxy server on port 8118...
* Dumping data to flows/log-1592095799.flows...
Traceback (most recent call last):
  File "/home/pi/.local/bin/mitmdump", line 6, in <module>
    from mitmproxy.tools.main import mitmdump
  File "/home/pi/.local/lib/python3.7/site-packages/mitmproxy/tools/main.py", line 22, in <module>
    from ._main import *  # noqa
  File "/home/pi/.local/lib/python3.7/site-packages/mitmproxy/tools/_main.py", line 17, in <module>
    from mitmproxy import proxy
  File "/home/pi/.local/lib/python3.7/site-packages/mitmproxy/proxy/__init__.py", line 2, in <module>
    from .root_context import RootContext
  File "/home/pi/.local/lib/python3.7/site-packages/mitmproxy/proxy/root_context.py", line 4, in <module>
    from mitmproxy.proxy import protocol
  File "/home/pi/.local/lib/python3.7/site-packages/mitmproxy/proxy/protocol/__init__.py", line 36, in <module>
    from .http2 import Http2Layer
  File "/home/pi/.local/lib/python3.7/site-packages/mitmproxy/proxy/protocol/http2.py", line 7, in <module>
    from h2 import connection
  File "/home/pi/.local/lib/python3.7/site-packages/h2/connection.py", line 23, in <module>
    from .events import (
  File "/home/pi/.local/lib/python3.7/site-packages/h2/events.py", line 14, in <module>
    from .settings import ChangedSetting, _setting_code_from_int
  File "/home/pi/.local/lib/python3.7/site-packages/h2/settings.py", line 25, in <module>
    class SettingCodes(enum.IntEnum):
  File "/home/pi/.local/lib/python3.7/site-packages/h2/settings.py", line 60, in SettingCodes
    ENABLE_CONNECT_PROTOCOL = SettingsFrame.ENABLE_CONNECT_PROTOCOL
AttributeError: type object 'SettingsFrame' has no attribute 'ENABLE_CONNECT_PROTOCOL'

**Comment by gschmidl** [comment]
The following got it to run for me:

```
pip3 install h2
pip3 install -U pyasn1
```
and change all instances of 're2.compile' to 're.compile' in adblock.py.

This still leaves one warning about re2 which I hope to also fix.

**Comment by epitron** [comment]
Thanks for the heads-up. It looks like I need to add some code to auto-detect whether `re2` is installed/functional, and fall back to `re` if not.

I'm having trouble building `re2` on Arch now (it looks like the Cython bindings are out of date).

**Comment by sarnold** [comment]
Can you try again with the latest pyre2 release?  The build system was updated/modernized and the platform wheels are all correctly built/repaired.  Everything should build clean on armv7/arm64, however, raspberrypi is still slow and under-powered (even compared to other "similar" speced arm devices.  Anyway, you should now be able to build pyre2 cleanly on any reasonable platform.
